version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Build started on $(date)"
      - |
        # Check if there are frontend changes
        if [ -n "$CODEBUILD_WEBHOOK_TRIGGER" ]; then
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || echo "")
          if echo "$CHANGED_FILES" | grep -q "^tasks-app/frontend/"; then
            echo "Frontend changes detected"
            export SHOULD_BUILD="true"
          else
            echo "No frontend changes detected, skipping build"
            export SHOULD_BUILD="false"
          fi
        else
          echo "Manual trigger or first build, building everything"
          export SHOULD_BUILD="true"
        fi
      - echo "SHOULD_BUILD=$SHOULD_BUILD"
      - |
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo "Getting API URL from SSM..."
          export REACT_APP_API_URL=$(aws ssm get-parameter --name /tasks-app/prod/api-url --query Parameter.Value --output text --region us-east-1)
          echo "API URL: $REACT_APP_API_URL"
          echo "Installing dependencies..."
          cd tasks-app/frontend
          npm install
        fi

  build:
    commands:
      - |
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo "Building React application..."
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
          echo "Build completed on $(date)"
        else
          echo "Skipping build"
        fi

  post_build:
    commands:
      - |
        if [ "$SHOULD_BUILD" = "true" ]; then
          echo "Deploying to S3..."
          aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
          echo "Frontend deployment completed!"
        else
          echo "Skipping deployment"
          mkdir -p build
          echo "skipped" > build/index.html
        fi

artifacts:
  files:
    - build/**/*

env:
  variables:
    NODE_ENV: production
    GENERATE_SOURCEMAP: "false"
    CI: "false"
  parameter-store:
    S3_BUCKET_NAME: /tasks-app/frontend/s3-bucket
