version: 0.2

# 🚀 CodeBuild para Frontend React
# Deploy automático para S3 + CloudFront
# Só executa se houver mudanças no frontend/

phases:
  install:
    runtime-versions:
      nodejs: 18

  pre_build:
    commands:
      - echo "Build started on $(date)"
      - echo "Installing dependencies..."
      - cd tasks-app/frontend
      - npm ci
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version

  build:
    commands:
      - echo "Building React application..."
      - npm run build
      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET_NAME --delete
      - echo "Frontend deployment completed!"

artifacts:
  files:
    - '**/*'
  base-directory: tasks-app/frontend/build
  name: frontend-build-$(date +%Y-%m-%d-%H-%M-%S)
  discard-paths: no

cache:
  paths:
    - frontend/node_modules/**/*

env:
  variables:
    NODE_ENV: production
    GENERATE_SOURCEMAP: "false"
    CI: "false"
  parameter-store:
    S3_BUCKET_NAME: /tasks-app/frontend/s3-bucket
